package cc.zyycc.launcher;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Properties;

public class ServerInitializer {
    public static void prepareServerDirectory(File serverDir) throws IOException {
        if (!serverDir.exists()) {
            serverDir.mkdirs();
        }
        File eula = new File(serverDir, "eula.txt");
        if (!checkEulaAccepted(eula)) {
            confirmEulaAndSave(eula);
        }
        File serverProperties = new File(serverDir, "server.properties");
        if (!serverProperties.exists()) {
            generateServerProperties(serverProperties);
        }
    }

    private static void generateServerProperties(File targetFile) throws IOException {
        if (targetFile.exists()) return;
        try (InputStream in = ServerInitializer.class.getClassLoader().getResourceAsStream("default-server.properties")) {
            if (in == null) throw new FileNotFoundException("default-server.properties not found in resources!");
            Properties props = new Properties();
            props.load(new InputStreamReader(in, StandardCharsets.UTF_8));

            try (Writer out = new OutputStreamWriter(Files.newOutputStream(targetFile.toPath()), StandardCharsets.UTF_8)) {
                props.store(out, "Generated by ZyyLauncher");
                System.out.println("✅ 已生成 server.properties：" + targetFile.getAbsolutePath());
            }
        }
    }

    private static void confirmEulaAndSave(File eula) throws IOException {

        System.out.println("⚠️ 你必须同意 Minecraft 的最终用户许可协议 (EULA) 才能启动服务器。");
        System.out.println("📄 请访问并阅读: https://aka.ms/MinecraftEULA");
        System.out.print("✅ 是否同意 EULA？输入 'yes' 同意: ");


        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        String input = reader.readLine();
        if ("yes".equalsIgnoreCase(input.trim())) {
            try (PrintWriter out = new PrintWriter(new FileWriter(eula))) {
                out.println("# By changing the setting below to TRUE you are indicating your agreement to our EULA.");
                out.println("# https://aka.ms/MinecraftEULA");
                out.println("eula=true");
            }
            System.out.println("✅ EULA 同意记录已保存，继续启动服务端...");
        } else {
            System.err.println("❌ 你没有同意 EULA，服务端将不会启动。");
            System.exit(0);
        }
    }

    private static boolean checkEulaAccepted(File eulaFile) {
        if (!eulaFile.exists()) return false;

        Properties props = new Properties();
        try (FileReader reader = new FileReader(eulaFile)) {
            props.load(reader);
        } catch (IOException e) {
            return false;
        }

        return "true".equalsIgnoreCase(props.getProperty("eula"));
    }
}
